services:
  - type: web
    name: artisan-lux-admin
    runtime: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
    healthCheckPath: /
