export type TaxonomyNode = {
  key: string;
  name: string;
  children?: TaxonomyNode[];
};

export const TAXONOMY: TaxonomyNode[] = [
  {
    key: "fashion",
    name: "Fashion",
    children: [
      { key: "fashion_men_clothing", name: "Men's Clothing" },
      { key: "fashion_men_shoes", name: "Men's Shoes" },
      { key: "fashion_women_clothing", name: "Women's Clothing" },
      { key: "fashion_women_shoes", name: "Women's Shoes" },
      { key: "fashion_accessories", name: "Accessories" },
      { key: "fashion_bags", name: "Bags" },
      { key: "fashion_jewelry", name: "Jewelry" },
      { key: "fashion_watches", name: "Watches" },
      { key: "fashion_kids_baby", name: "Kids & Baby" },
      { key: "fashion_sportswear", name: "Sportswear" },
    ],
  },
  {
    key: "electronics",
    name: "Electronics",
    children: [
      { key: "electronics_mobiles", name: "Mobile Phones" },
      { key: "electronics_computing", name: "Computers & Laptops" },
      { key: "electronics_tvs", name: "TVs & Home Theater" },
      { key: "electronics_audio", name: "Audio" },
      { key: "electronics_cameras", name: "Cameras & Drones" },
      { key: "electronics_gaming", name: "Gaming" },
      { key: "electronics_wearables", name: "Wearables" },
      { key: "electronics_accessories", name: "Accessories" },
      { key: "electronics_smart_home", name: "Smart Home" },
    ],
  },
  {
    key: "home_living",
    name: "Home & Living",
    children: [
      { key: "home_furniture", name: "Furniture" },
      { key: "home_kitchen_dining", name: "Kitchen & Dining" },
      { key: "home_appliances", name: "Appliances" },
      { key: "home_bed_bath", name: "Bed & Bath" },
      { key: "home_textiles", name: "Textiles" },
      { key: "home_lighting", name: "Lighting" },
      { key: "home_decor", name: "Decor" },
      { key: "home_storage_organization", name: "Storage & Organization" },
      { key: "home_tools_improvement", name: "Tools & Home Improvement" },
    ],
  },
  {
    key: "groceries",
    name: "Groceries & Food",
    children: [
      { key: "groceries_fruits_vegetables", name: "Fruits & Vegetables" },
      { key: "groceries_meat_seafood", name: "Meat & Seafood" },
      { key: "groceries_dairy_eggs", name: "Dairy & Eggs" },
      { key: "groceries_bakery", name: "Bakery" },
      { key: "groceries_pantry", name: "Pantry Staples" },
      { key: "groceries_snacks", name: "Snacks" },
      { key: "groceries_beverages", name: "Beverages (Non‑Alcoholic)" },
      { key: "groceries_frozen", name: "Frozen" },
      { key: "groceries_organic", name: "Organic & Specialty" },
    ],
  },
  {
    key: "alcohol",
    name: "Liquor, Beer & Wine",
    children: [
      { key: "alcohol_beer", name: "Beer" },
      { key: "alcohol_wine", name: "Wine" },
      { key: "alcohol_spirits", name: "Spirits" },
      { key: "alcohol_ciders_seltzers", name: "Ciders & Seltzers" },
      { key: "alcohol_mixers", name: "Mixers & Barware" },
    ],
  },
  {
    key: "vehicles_automotive",
    name: "Vehicles & Automotive",
    children: [
      { key: "vehicles_cars", name: "Cars" },
      { key: "vehicles_motorcycles", name: "Motorcycles" },
      { key: "vehicles_trucks_vans", name: "Trucks & Vans" },
      { key: "vehicles_parts", name: "Auto Parts" },
      { key: "vehicles_tires_batteries", name: "Tires & Batteries" },
      { key: "vehicles_accessories_interior", name: "Interior Accessories" },
      { key: "vehicles_accessories_exterior", name: "Exterior Accessories" },
      { key: "vehicles_tools_equipment", name: "Tools & Equipment" },
    ],
  },
  {
    key: "sports_fitness",
    name: "Sports & Fitness",
    children: [
      { key: "sports_exercise_fitness", name: "Exercise & Fitness" },
      { key: "sports_outdoor_recreation", name: "Outdoor Recreation" },
      { key: "sports_team_sports", name: "Team Sports" },
      { key: "sports_cycling", name: "Cycling" },
      { key: "sports_running", name: "Running" },
      { key: "sports_swimming", name: "Swimming" },
    ],
  },
  {
    key: "beauty_grooming",
    name: "Beauty & Grooming",
    children: [
      { key: "beauty_skincare", name: "Skincare" },
      { key: "beauty_makeup", name: "Makeup" },
      { key: "beauty_fragrance", name: "Fragrance" },
      { key: "beauty_haircare", name: "Haircare" },
      { key: "beauty_tools", name: "Beauty Tools" },
    ],
  },
  {
    key: "health_wellness",
    name: "Health & Wellness",
    children: [
      { key: "health_supplements", name: "Vitamins & Supplements" },
      { key: "health_personal_care", name: "Personal Care" },
      { key: "health_medical_supplies", name: "Medical Supplies" },
      { key: "health_mobility_aids", name: "Mobility Aids" },
    ],
  },
  {
    key: "baby_kids",
    name: "Baby & Kids",
    children: [
      { key: "baby_essentials", name: "Baby Essentials" },
      { key: "baby_strollers_car_seats", name: "Strollers & Car Seats" },
      { key: "kids_clothing", name: "Kids' Clothing" },
      { key: "kids_toys_education", name: "Toys & Education" },
    ],
  },
  {
    key: "books_media",
    name: "Books & Media",
    children: [
      { key: "books_print", name: "Books" },
      { key: "books_ebooks", name: "eBooks" },
      { key: "media_movies_tv", name: "Movies & TV" },
      { key: "media_music", name: "Music" },
      { key: "media_magazines", name: "Magazines" },
    ],
  },
  {
    key: "pets",
    name: "Pets & Animals",
    children: [
      { key: "pets_food", name: "Pet Food" },
      { key: "pets_supplies", name: "Pet Supplies" },
      { key: "pets_grooming", name: "Grooming" },
      { key: "pets_health", name: "Pet Health" },
    ],
  },
  {
    key: "office_school",
    name: "Office & School",
    children: [
      { key: "office_supplies", name: "Office Supplies" },
      { key: "office_stationery", name: "Stationery" },
      { key: "office_printers", name: "Printers & Ink" },
      { key: "office_furniture", name: "Office Furniture" },
    ],
  },
  {
    key: "industrial_scientific",
    name: "Industrial & Scientific",
    children: [
      { key: "industrial_tools", name: "Industrial Tools" },
      { key: "industrial_safety", name: "Safety" },
      { key: "scientific_lab", name: "Lab Supplies" },
    ],
  },
  {
    key: "art_collectibles",
    name: "Art & Collectibles",
    children: [
      { key: "art_paintings", name: "Paintings" },
      { key: "art_sculpture", name: "Sculpture" },
      { key: "art_prints", name: "Prints" },
      { key: "art_photography", name: "Photography" },
      { key: "art_antiques", name: "Antiques" },
      { key: "art_memorabilia", name: "Memorabilia" },
    ],
  },
  {
    key: "outdoor_garden",
    name: "Outdoor & Garden",
    children: [
      { key: "outdoor_furniture", name: "Outdoor Furniture" },
      { key: "outdoor_garden_tools", name: "Garden Tools" },
      { key: "outdoor_grills", name: "Grills & Outdoor Cooking" },
      { key: "outdoor_decor", name: "Outdoor Decor" },
      { key: "outdoor_camping", name: "Camping & Hiking" },
    ],
  },
  {
    key: "toys_games",
    name: "Toys & Games",
    children: [
      { key: "toys_educational", name: "Educational" },
      { key: "toys_collectibles", name: "Collectibles" },
      { key: "toys_puzzles", name: "Puzzles" },
      { key: "toys_boardgames", name: "Board Games" },
      { key: "toys_action_figures", name: "Action Figures" },
      { key: "toys_dolls", name: "Dolls & Plush" },
    ],
  },
  {
    key: "music_instruments",
    name: "Musical Instruments",
    children: [
      { key: "music_guitars", name: "Guitars" },
      { key: "music_keyboards", name: "Keyboards & Pianos" },
      { key: "music_drums", name: "Drums & Percussion" },
      { key: "music_recording", name: "Recording & Studio" },
    ],
  },
  {
    key: "farming_agriculture",
    name: "Farming & Agriculture",
    children: [
      { key: "farming_equipment", name: "Farm Equipment" },
      { key: "farming_seeds", name: "Seeds & Fertilizers" },
      { key: "farming_livestock", name: "Livestock & Feed" },
    ],
  },
  {
    key: "travel_luggage",
    name: "Travel & Luggage",
    children: [
      { key: "travel_luggage_bags", name: "Luggage & Bags" },
      { key: "travel_accessories", name: "Travel Accessories" },
    ],
  },
  {
    key: "food_beverages",
    name: "Food & Beverages",
    children: [
      { key: "food_restaurants", name: "Restaurants & Dining" },
      { key: "food_fast_food", name: "Fast Food" },
      { key: "food_coffee_tea", name: "Coffee & Tea" },
      { key: "food_bakery_confectionery", name: "Bakery & Confectionery" },
      { key: "food_specialty_gourmet", name: "Specialty & Gourmet" },
      { key: "food_international_cuisine", name: "International Cuisine" },
      { key: "food_catering_services", name: "Catering Services" },
      { key: "food_meal_kits", name: "Meal Kits & Prep" },
    ],
  },
  {
    key: "energy_utilities",
    name: "Energy & Utilities",
    children: [
      { key: "energy_solar_panels", name: "Solar Panels" },
      { key: "energy_wind_power", name: "Wind Power" },
      { key: "energy_generators", name: "Generators" },
      { key: "energy_batteries", name: "Energy Storage" },
      { key: "utilities_water_filtration", name: "Water Filtration" },
      { key: "utilities_hvac", name: "HVAC Systems" },
      { key: "utilities_electrical_supplies", name: "Electrical Supplies" },
    ],
  },
  {
    key: "textiles_clothing",
    name: "Textiles & Clothing Materials",
    children: [
      { key: "textiles_fabrics", name: "Fabrics" },
      { key: "textiles_threads_yarns", name: "Threads & Yarns" },
      { key: "textiles_sewing_supplies", name: "Sewing Supplies" },
      { key: "textiles_patterns", name: "Patterns" },
      { key: "textiles_leather_goods", name: "Leather & Materials" },
    ],
  },
  {
    key: "marine_nautical",
    name: "Marine & Nautical",
    children: [
      { key: "marine_boats_yachts", name: "Boats & Yachts" },
      { key: "marine_fishing_gear", name: "Fishing Equipment" },
      { key: "marine_navigation", name: "Navigation Equipment" },
      { key: "marine_safety", name: "Marine Safety" },
      { key: "marine_parts_accessories", name: "Marine Parts & Accessories" },
    ],
  },
  {
    key: "aviation_aerospace",
    name: "Aviation & Aerospace",
    children: [
      { key: "aviation_aircraft", name: "Aircraft" },
      { key: "aviation_drones", name: "Drones & UAVs" },
      { key: "aviation_parts", name: "Aviation Parts" },
      { key: "aviation_navigation", name: "Flight Navigation" },
      { key: "aviation_training", name: "Aviation Training" },
    ],
  },
  {
    key: "mining_geology",
    name: "Mining & Geology",
    children: [
      { key: "mining_equipment", name: "Mining Equipment" },
      { key: "mining_safety_gear", name: "Mining Safety" },
      { key: "geology_instruments", name: "Geological Instruments" },
      { key: "mining_precious_metals", name: "Precious Metals" },
      { key: "mining_gems_stones", name: "Gems & Stones" },
    ],
  },
  {
    key: "security_surveillance",
    name: "Security & Surveillance",
    children: [
      { key: "security_cameras", name: "Security Cameras" },
      { key: "security_alarms", name: "Alarm Systems" },
      { key: "security_access_control", name: "Access Control" },
      { key: "security_safes_vaults", name: "Safes & Vaults" },
      { key: "security_personal_protection", name: "Personal Protection" },
    ],
  },
  {
    key: "telecommunications",
    name: "Telecommunications",
    children: [
      { key: "telecom_phones", name: "Phones & Systems" },
      { key: "telecom_networking", name: "Networking Equipment" },
      { key: "telecom_radio", name: "Radio Equipment" },
      { key: "telecom_satellite", name: "Satellite Equipment" },
      { key: "telecom_fiber_optics", name: "Fiber Optics" },
    ],
  },
  {
    key: "waste_recycling",
    name: "Waste & Recycling",
    children: [
      { key: "waste_bins_containers", name: "Bins & Containers" },
      { key: "waste_processing", name: "Processing Equipment" },
      { key: "recycling_materials", name: "Recycling Materials" },
      { key: "waste_composting", name: "Composting" },
      { key: "waste_hazardous", name: "Hazardous Waste" },
    ],
  },
  {
    key: "military_defense",
    name: "Military & Defense",
    children: [
      { key: "military_tactical_gear", name: "Tactical Gear" },
      { key: "military_survival", name: "Survival Equipment" },
      { key: "military_communications", name: "Military Communications" },
      { key: "military_training", name: "Training Equipment" },
      { key: "military_collectibles", name: "Military Collectibles" },
    ],
  },
  {
    key: "emergency_services",
    name: "Emergency Services",
    children: [
      { key: "emergency_medical", name: "Emergency Medical" },
      { key: "emergency_fire_safety", name: "Fire Safety" },
      { key: "emergency_rescue", name: "Rescue Equipment" },
      { key: "emergency_disaster_prep", name: "Disaster Preparedness" },
      { key: "emergency_first_aid", name: "First Aid" },
    ],
  },
  {
    key: "services",
    name: "Services",
    children: [
      // Home & Property Services
      { key: "services_home_cleaning", name: "Home Cleaning" },
      { key: "services_deep_cleaning", name: "Deep Cleaning" },
      { key: "services_carpet_cleaning", name: "Carpet & Upholstery Cleaning" },
      { key: "services_window_cleaning", name: "Window Cleaning" },
      { key: "services_pressure_washing", name: "Pressure Washing" },
      { key: "services_plumbing", name: "Plumbing" },
      { key: "services_drain_cleaning", name: "Drain Cleaning" },
      { key: "services_water_heater", name: "Water Heater Services" },
      { key: "services_electrical", name: "Electrical" },
      { key: "services_electrical_repair", name: "Electrical Repair" },
      { key: "services_electrical_installation", name: "Electrical Installation" },
      { key: "services_carpentry", name: "Carpentry" },
      { key: "services_cabinet_making", name: "Cabinet Making" },
      { key: "services_flooring", name: "Flooring Installation" },
      { key: "services_painting", name: "Painting" },
      { key: "services_wallpaper", name: "Wallpaper Installation" },
      { key: "services_drywall", name: "Drywall & Plastering" },
      { key: "services_roofing", name: "Roofing" },
      { key: "services_gutter_cleaning", name: "Gutter Cleaning" },
      { key: "services_appliance_repair", name: "Appliance Repair" },
      { key: "services_appliance_installation", name: "Appliance Installation" },
      { key: "services_hvac", name: "HVAC Services" },
      { key: "services_air_conditioning", name: "Air Conditioning" },
      { key: "services_heating", name: "Heating Services" },
      { key: "services_duct_cleaning", name: "Duct Cleaning" },
      { key: "services_insulation", name: "Insulation" },
      { key: "services_waterproofing", name: "Waterproofing" },
      { key: "services_foundation_repair", name: "Foundation Repair" },
      { key: "services_moving", name: "Moving & Relocation" },
      { key: "services_packing", name: "Packing Services" },
      { key: "services_storage", name: "Storage Services" },
      { key: "services_landscaping", name: "Landscaping & Gardening" },
      { key: "services_lawn_care", name: "Lawn Care" },
      { key: "services_tree_services", name: "Tree Services" },
      { key: "services_irrigation", name: "Irrigation Systems" },
      { key: "services_snow_removal", name: "Snow Removal" },
      { key: "services_pest_control", name: "Pest Control" },
      { key: "services_termite_control", name: "Termite Control" },
      { key: "services_wildlife_removal", name: "Wildlife Removal" },
      { key: "services_home_security", name: "Home Security" },
      { key: "services_locksmith", name: "Locksmith" },
      { key: "services_alarm_systems", name: "Alarm Systems" },
      { key: "services_interior_design", name: "Interior Design" },
      { key: "services_home_staging", name: "Home Staging" },
      { key: "services_feng_shui", name: "Feng Shui Consulting" },
      { key: "services_construction", name: "Construction & Renovation" },
      { key: "services_demolition", name: "Demolition" },
      { key: "services_general_contracting", name: "General Contracting" },
      { key: "services_architectural", name: "Architectural Services" },
      { key: "services_engineering", name: "Engineering Services" },
      { key: "services_surveying", name: "Land Surveying" },
      { key: "services_permits", name: "Permit Services" },
      { key: "services_inspection", name: "Home Inspection" },
      { key: "services_appraisal", name: "Property Appraisal" },
      
      // Automotive Services
      { key: "services_auto_repair", name: "Auto Repair" },
      { key: "services_oil_change", name: "Oil Change" },
      { key: "services_brake_repair", name: "Brake Repair" },
      { key: "services_transmission", name: "Transmission Repair" },
      { key: "services_engine_repair", name: "Engine Repair" },
      { key: "services_tire_services", name: "Tire Services" },
      { key: "services_wheel_alignment", name: "Wheel Alignment" },
      { key: "services_auto_body", name: "Auto Body Repair" },
      { key: "services_paint_repair", name: "Auto Paint Repair" },
      { key: "services_windshield", name: "Windshield Repair" },
      { key: "services_car_wash", name: "Car Wash & Detailing" },
      { key: "services_car_detailing", name: "Car Detailing" },
      { key: "services_ceramic_coating", name: "Ceramic Coating" },
      { key: "services_towing", name: "Towing" },
      { key: "services_roadside_assistance", name: "Roadside Assistance" },
      { key: "services_auto_glass", name: "Auto Glass" },
      { key: "services_auto_electrical", name: "Auto Electrical" },
      { key: "services_auto_ac", name: "Auto Air Conditioning" },
      { key: "services_car_rental", name: "Car Rental" },
      { key: "services_rv_repair", name: "RV Repair" },
      { key: "services_motorcycle_repair", name: "Motorcycle Repair" },
      
      // Beauty & Wellness Services
      { key: "services_beauty_salon", name: "Beauty Salon" },
      { key: "services_hair_salon", name: "Hair Salon" },
      { key: "services_hair_coloring", name: "Hair Coloring" },
      { key: "services_hair_extensions", name: "Hair Extensions" },
      { key: "services_barber", name: "Barber" },
      { key: "services_beard_grooming", name: "Beard Grooming" },
      { key: "services_makeup", name: "Makeup Artists" },
      { key: "services_bridal_makeup", name: "Bridal Makeup" },
      { key: "services_special_effects_makeup", name: "Special Effects Makeup" },
      { key: "services_eyebrow_threading", name: "Eyebrow Threading" },
      { key: "services_microblading", name: "Microblading" },
      { key: "services_eyelash_extensions", name: "Eyelash Extensions" },
      { key: "services_facials", name: "Facials" },
      { key: "services_skincare", name: "Skincare Treatments" },
      { key: "services_chemical_peels", name: "Chemical Peels" },
      { key: "services_microdermabrasion", name: "Microdermabrasion" },
      { key: "services_botox", name: "Botox & Injectables" },
      { key: "services_laser_treatments", name: "Laser Treatments" },
      { key: "services_laser_hair_removal", name: "Laser Hair Removal" },
      { key: "services_tattoo", name: "Tattoo Services" },
      { key: "services_tattoo_removal", name: "Tattoo Removal" },
      { key: "services_piercing", name: "Body Piercing" },
      { key: "services_nail_salon", name: "Nail Salon" },
      { key: "services_manicure_pedicure", name: "Manicure & Pedicure" },
      { key: "services_nail_art", name: "Nail Art" },
      { key: "services_spa_massage", name: "Spa & Massage" },
      { key: "services_deep_tissue_massage", name: "Deep Tissue Massage" },
      { key: "services_hot_stone_massage", name: "Hot Stone Massage" },
      { key: "services_prenatal_massage", name: "Prenatal Massage" },
      { key: "services_couples_massage", name: "Couples Massage" },
      { key: "services_reflexology", name: "Reflexology" },
      { key: "services_acupuncture", name: "Acupuncture" },
      { key: "services_cupping", name: "Cupping Therapy" },
      { key: "services_aromatherapy", name: "Aromatherapy" },
      { key: "services_reiki", name: "Reiki" },
      { key: "services_meditation", name: "Meditation Instruction" },
      { key: "services_yoga_instruction", name: "Yoga Instruction" },
      { key: "services_pilates", name: "Pilates Instruction" },
      
      // Health & Fitness Services
      { key: "services_personal_training", name: "Personal Training" },
      { key: "services_group_fitness", name: "Group Fitness Classes" },
      { key: "services_crossfit", name: "CrossFit Training" },
      { key: "services_martial_arts", name: "Martial Arts Instruction" },
      { key: "services_boxing", name: "Boxing Training" },
      { key: "services_swimming_lessons", name: "Swimming Lessons" },
      { key: "services_dance_lessons", name: "Dance Lessons" },
      { key: "services_sports_coaching", name: "Sports Coaching" },
      { key: "services_nutrition", name: "Nutrition & Diet" },
      { key: "services_meal_planning", name: "Meal Planning" },
      { key: "services_weight_loss", name: "Weight Loss Coaching" },
      { key: "services_life_coaching", name: "Life Coaching" },
      { key: "services_wellness_coaching", name: "Wellness Coaching" },
      { key: "services_mental_health", name: "Mental Health Counseling" },
      { key: "services_therapy", name: "Therapy Services" },
      { key: "services_couples_therapy", name: "Couples Therapy" },
      { key: "services_family_therapy", name: "Family Therapy" },
      { key: "services_addiction_counseling", name: "Addiction Counseling" },
      { key: "services_grief_counseling", name: "Grief Counseling" },
      { key: "services_career_counseling", name: "Career Counseling" },
      
      // Medical & Healthcare Services
      { key: "services_medical", name: "Medical Consultation" },
      { key: "services_telemedicine", name: "Telemedicine" },
      { key: "services_urgent_care", name: "Urgent Care" },
      { key: "services_family_medicine", name: "Family Medicine" },
      { key: "services_internal_medicine", name: "Internal Medicine" },
      { key: "services_pediatrics", name: "Pediatrics" },
      { key: "services_geriatrics", name: "Geriatrics" },
      { key: "services_cardiology", name: "Cardiology" },
      { key: "services_dermatology", name: "Dermatology" },
      { key: "services_orthopedics", name: "Orthopedics" },
      { key: "services_neurology", name: "Neurology" },
      { key: "services_psychiatry", name: "Psychiatry" },
      { key: "services_physical_therapy", name: "Physical Therapy" },
      { key: "services_occupational_therapy", name: "Occupational Therapy" },
      { key: "services_speech_therapy", name: "Speech Therapy" },
      { key: "services_chiropractic", name: "Chiropractic" },
      { key: "services_dental", name: "Dental" },
      { key: "services_dental_cleaning", name: "Dental Cleaning" },
      { key: "services_orthodontics", name: "Orthodontics" },
      { key: "services_oral_surgery", name: "Oral Surgery" },
      { key: "services_cosmetic_dentistry", name: "Cosmetic Dentistry" },
      { key: "services_periodontics", name: "Periodontics" },
      { key: "services_endodontics", name: "Endodontics" },
      { key: "services_optometry", name: "Optometry" },
      { key: "services_ophthalmology", name: "Ophthalmology" },
      { key: "services_audiology", name: "Audiology" },
      { key: "services_podiatry", name: "Podiatry" },
      { key: "services_pharmacy", name: "Pharmacy Services" },
      { key: "services_medical_imaging", name: "Medical Imaging" },
      { key: "services_laboratory", name: "Laboratory Services" },
      { key: "services_home_healthcare", name: "Home Healthcare" },
      { key: "services_nursing", name: "Nursing Services" },
      { key: "services_eldercare", name: "Elder Care" },
      { key: "services_hospice", name: "Hospice Care" },
      { key: "services_medical_equipment", name: "Medical Equipment Rental" },
      
      // Veterinary Services
      { key: "services_veterinary", name: "Veterinary Services" },
      { key: "services_pet_grooming", name: "Pet Grooming" },
      { key: "services_pet_boarding", name: "Pet Boarding" },
      { key: "services_pet_daycare", name: "Pet Daycare" },
      { key: "services_pet_sitting", name: "Pet Sitting" },
      { key: "services_dog_walking", name: "Dog Walking" },
      { key: "services_pet_training", name: "Pet Training" },
      { key: "services_dog_training", name: "Dog Training" },
      { key: "services_pet_photography", name: "Pet Photography" },
      { key: "services_pet_taxi", name: "Pet Transportation" },
      { key: "services_mobile_vet", name: "Mobile Veterinary" },
      { key: "services_pet_cremation", name: "Pet Cremation" },
      
      // Education & Training Services
      { key: "services_tutoring", name: "Tutoring" },
      { key: "services_test_prep", name: "Test Preparation" },
      { key: "services_sat_prep", name: "SAT Preparation" },
      { key: "services_gmat_prep", name: "GMAT Preparation" },
      { key: "services_college_counseling", name: "College Counseling" },
      { key: "services_academic_coaching", name: "Academic Coaching" },
      { key: "services_homeschool_support", name: "Homeschool Support" },
      { key: "services_special_needs_tutoring", name: "Special Needs Tutoring" },
      { key: "services_music_lessons", name: "Music Lessons" },
      { key: "services_piano_lessons", name: "Piano Lessons" },
      { key: "services_guitar_lessons", name: "Guitar Lessons" },
      { key: "services_voice_lessons", name: "Voice Lessons" },
      { key: "services_drum_lessons", name: "Drum Lessons" },
      { key: "services_violin_lessons", name: "Violin Lessons" },
      { key: "services_art_lessons", name: "Art Lessons" },
      { key: "services_painting_classes", name: "Painting Classes" },
      { key: "services_pottery_classes", name: "Pottery Classes" },
      { key: "services_photography_classes", name: "Photography Classes" },
      { key: "services_cooking_classes", name: "Cooking Classes" },
      { key: "services_language_classes", name: "Language Classes" },
      { key: "services_esl", name: "ESL Instruction" },
      { key: "services_spanish_lessons", name: "Spanish Lessons" },
      { key: "services_french_lessons", name: "French Lessons" },
      { key: "services_german_lessons", name: "German Lessons" },
      { key: "services_mandarin_lessons", name: "Mandarin Lessons" },
      { key: "services_computer_training", name: "Computer Training" },
      { key: "services_coding_classes", name: "Coding Classes" },
      { key: "services_microsoft_office", name: "Microsoft Office Training" },
      { key: "services_adobe_training", name: "Adobe Software Training" },
      { key: "services_driving_lessons", name: "Driving Lessons" },
      { key: "services_motorcycle_lessons", name: "Motorcycle Lessons" },
      { key: "services_flight_training", name: "Flight Training" },
      { key: "services_boating_lessons", name: "Boating Lessons" },
      
      // Creative Services
      { key: "services_photography", name: "Photography" },
      { key: "services_wedding_photography", name: "Wedding Photography" },
      { key: "services_portrait_photography", name: "Portrait Photography" },
      { key: "services_event_photography", name: "Event Photography" },
      { key: "services_real_estate_photography", name: "Real Estate Photography" },
      { key: "services_product_photography", name: "Product Photography" },
      { key: "services_fashion_photography", name: "Fashion Photography" },
      { key: "services_headshot_photography", name: "Headshot Photography" },
      { key: "services_newborn_photography", name: "Newborn Photography" },
      { key: "services_family_photography", name: "Family Photography" },
      { key: "services_sports_photography", name: "Sports Photography" },
      { key: "services_drone_photography", name: "Drone Photography" },
      { key: "services_videography", name: "Videography" },
      { key: "services_wedding_videography", name: "Wedding Videography" },
      { key: "services_commercial_videography", name: "Commercial Videography" },
      { key: "services_music_videos", name: "Music Video Production" },
      { key: "services_documentary", name: "Documentary Production" },
      { key: "services_video_editing", name: "Video Editing" },
      { key: "services_animation", name: "Animation Services" },
      { key: "services_motion_graphics", name: "Motion Graphics" },
      { key: "services_3d_modeling", name: "3D Modeling" },
      { key: "services_cgi", name: "CGI Services" },
      { key: "services_graphic_design", name: "Graphic Design" },
      { key: "services_logo_design", name: "Logo Design" },
      { key: "services_branding", name: "Branding" },
      { key: "services_print_design", name: "Print Design" },
      { key: "services_packaging_design", name: "Packaging Design" },
      { key: "services_ui_ux_design", name: "UI/UX Design" },
      { key: "services_illustration", name: "Illustration" },
      { key: "services_cartoon_illustration", name: "Cartoon Illustration" },
      { key: "services_technical_illustration", name: "Technical Illustration" },
      { key: "services_architectural_rendering", name: "Architectural Rendering" },
      { key: "services_copywriting", name: "Copywriting" },
      { key: "services_content_writing", name: "Content Writing" },
      { key: "services_technical_writing", name: "Technical Writing" },
      { key: "services_ghostwriting", name: "Ghostwriting" },
      { key: "services_editing_proofreading", name: "Editing & Proofreading" },
      { key: "services_translation", name: "Translation Services" },
      { key: "services_transcription", name: "Transcription Services" },
      { key: "services_voice_over", name: "Voice Over Services" },
      { key: "services_audio_production", name: "Audio Production" },
      { key: "services_podcast_production", name: "Podcast Production" },
      { key: "services_music_production", name: "Music Production" },
      { key: "services_sound_design", name: "Sound Design" },
      { key: "services_audio_mixing", name: "Audio Mixing" },
      { key: "services_mastering", name: "Audio Mastering" },
      { key: "services_jingle_production", name: "Jingle Production" },
      
      // Technology Services
      { key: "services_web_development", name: "Web Development" },
      { key: "services_website_design", name: "Website Design" },
      { key: "services_ecommerce_development", name: "E-commerce Development" },
      { key: "services_wordpress_development", name: "WordPress Development" },
      { key: "services_shopify_development", name: "Shopify Development" },
      { key: "services_custom_software", name: "Custom Software Development" },
      { key: "services_app_development", name: "App Development" },
      { key: "services_ios_development", name: "iOS Development" },
      { key: "services_android_development", name: "Android Development" },
      { key: "services_game_development", name: "Game Development" },
      { key: "services_ar_vr_development", name: "AR/VR Development" },
      { key: "services_blockchain_development", name: "Blockchain Development" },
      { key: "services_ai_development", name: "AI Development" },
      { key: "services_machine_learning", name: "Machine Learning" },
      { key: "services_data_science", name: "Data Science" },
      { key: "services_database_development", name: "Database Development" },
      { key: "services_cloud_services", name: "Cloud Services" },
      { key: "services_devops", name: "DevOps" },
      { key: "services_cybersecurity", name: "Cybersecurity" },
      { key: "services_penetration_testing", name: "Penetration Testing" },
      { key: "services_it_support", name: "IT Support" },
      { key: "services_computer_repair", name: "Computer Repair" },
      { key: "services_laptop_repair", name: "Laptop Repair" },
      { key: "services_phone_repair", name: "Phone Repair" },
      { key: "services_data_recovery", name: "Data Recovery" },
      { key: "services_network_setup", name: "Network Setup" },
      { key: "services_server_maintenance", name: "Server Maintenance" },
      { key: "services_software_installation", name: "Software Installation" },
      { key: "services_virus_removal", name: "Virus Removal" },
      { key: "services_tech_consulting", name: "Technology Consulting" },
      
      // Marketing & Business Services
      { key: "services_digital_marketing", name: "Digital Marketing" },
      { key: "services_seo_sem", name: "SEO & SEM" },
      { key: "services_ppc_advertising", name: "PPC Advertising" },
      { key: "services_google_ads", name: "Google Ads Management" },
      { key: "services_facebook_ads", name: "Facebook Ads Management" },
      { key: "services_social_media", name: "Social Media Management" },
      { key: "services_social_media_strategy", name: "Social Media Strategy" },
      { key: "services_influencer_marketing", name: "Influencer Marketing" },
      { key: "services_email_marketing", name: "Email Marketing" },
      { key: "services_affiliate_marketing", name: "Affiliate Marketing" },
      { key: "services_conversion_optimization", name: "Conversion Optimization" },
      { key: "services_analytics", name: "Analytics & Reporting" },
      { key: "services_market_research", name: "Market Research" },
      { key: "services_competitive_analysis", name: "Competitive Analysis" },
      { key: "services_brand_strategy", name: "Brand Strategy" },
      { key: "services_public_relations", name: "Public Relations" },
      { key: "services_press_releases", name: "Press Releases" },
      { key: "services_crisis_management", name: "Crisis Management" },
      { key: "services_lead_generation", name: "Lead Generation" },
      { key: "services_sales_funnel", name: "Sales Funnel Development" },
      { key: "services_crm_setup", name: "CRM Setup" },
      { key: "services_marketing_automation", name: "Marketing Automation" },
      { key: "services_print_advertising", name: "Print Advertising" },
      { key: "services_radio_advertising", name: "Radio Advertising" },
      { key: "services_tv_advertising", name: "TV Advertising" },
      { key: "services_outdoor_advertising", name: "Outdoor Advertising" },
      { key: "services_trade_shows", name: "Trade Show Services" },
      
      // Business & Professional Services
      { key: "services_business_consulting", name: "Business Consulting" },
      { key: "services_strategy_consulting", name: "Strategy Consulting" },
      { key: "services_management_consulting", name: "Management Consulting" },
      { key: "services_operations_consulting", name: "Operations Consulting" },
      { key: "services_hr_consulting", name: "HR Consulting" },
      { key: "services_recruitment", name: "Recruitment Services" },
      { key: "services_executive_search", name: "Executive Search" },
      { key: "services_temp_staffing", name: "Temporary Staffing" },
      { key: "services_payroll", name: "Payroll Services" },
      { key: "services_benefits_administration", name: "Benefits Administration" },
      { key: "services_employee_training", name: "Employee Training" },
      { key: "services_team_building", name: "Team Building" },
      { key: "services_leadership_training", name: "Leadership Training" },
      { key: "services_project_management", name: "Project Management" },
      { key: "services_change_management", name: "Change Management" },
      { key: "services_process_improvement", name: "Process Improvement" },
      { key: "services_quality_assurance", name: "Quality Assurance" },
      { key: "services_iso_certification", name: "ISO Certification" },
      { key: "services_compliance_consulting", name: "Compliance Consulting" },
      { key: "services_risk_management", name: "Risk Management" },
      { key: "services_business_valuation", name: "Business Valuation" },
      { key: "services_mergers_acquisitions", name: "Mergers & Acquisitions" },
      { key: "services_due_diligence", name: "Due Diligence" },
      { key: "services_business_plan", name: "Business Plan Writing" },
      { key: "services_grant_writing", name: "Grant Writing" },
      { key: "services_fundraising", name: "Fundraising" },
      { key: "services_investor_relations", name: "Investor Relations" },
      { key: "services_startup_consulting", name: "Startup Consulting" },
      { key: "services_franchise_consulting", name: "Franchise Consulting" },
      { key: "services_export_import", name: "Export/Import Consulting" },
      { key: "services_international_business", name: "International Business" },
      
      // Legal Services
      { key: "services_legal", name: "Legal Services" },
      { key: "services_corporate_law", name: "Corporate Law" },
      { key: "services_business_formation", name: "Business Formation" },
      { key: "services_contract_law", name: "Contract Law" },
      { key: "services_employment_law", name: "Employment Law" },
      { key: "services_intellectual_property", name: "Intellectual Property" },
      { key: "services_patent_law", name: "Patent Law" },
      { key: "services_trademark_law", name: "Trademark Law" },
      { key: "services_copyright_law", name: "Copyright Law" },
      { key: "services_real_estate_law", name: "Real Estate Law" },
      { key: "services_family_law", name: "Family Law" },
      { key: "services_divorce_law", name: "Divorce Law" },
      { key: "services_custody_law", name: "Child Custody Law" },
      { key: "services_adoption_law", name: "Adoption Law" },
      { key: "services_estate_planning", name: "Estate Planning" },
      { key: "services_probate_law", name: "Probate Law" },
      { key: "services_tax_law", name: "Tax Law" },
      { key: "services_criminal_law", name: "Criminal Law" },
      { key: "services_personal_injury", name: "Personal Injury Law" },
      { key: "services_medical_malpractice", name: "Medical Malpractice" },
      { key: "services_workers_compensation", name: "Workers' Compensation" },
      { key: "services_social_security_disability", name: "Social Security Disability" },
      { key: "services_immigration_law", name: "Immigration Law" },
      { key: "services_bankruptcy_law", name: "Bankruptcy Law" },
      { key: "services_consumer_protection", name: "Consumer Protection" },
      { key: "services_environmental_law", name: "Environmental Law" },
      { key: "services_construction_law", name: "Construction Law" },
      { key: "services_maritime_law", name: "Maritime Law" },
      { key: "services_aviation_law", name: "Aviation Law" },
      { key: "services_entertainment_law", name: "Entertainment Law" },
      { key: "services_sports_law", name: "Sports Law" },
      { key: "services_mediation", name: "Mediation" },
      { key: "services_arbitration", name: "Arbitration" },
      { key: "services_notary", name: "Notary Services" },
      { key: "services_legal_document_prep", name: "Legal Document Preparation" },
      { key: "services_paralegal", name: "Paralegal Services" },
      { key: "services_court_reporting", name: "Court Reporting" },
      { key: "services_legal_research", name: "Legal Research" },
      { key: "services_litigation_support", name: "Litigation Support" },
      
      // Financial Services
      { key: "services_accounting", name: "Accounting & Bookkeeping" },
      { key: "services_bookkeeping", name: "Bookkeeping" },
      { key: "services_cpa", name: "CPA Services" },
      { key: "services_tax_preparation", name: "Tax Preparation" },
      { key: "services_tax_planning", name: "Tax Planning" },
      { key: "services_payroll_processing", name: "Payroll Processing" },
      { key: "services_financial_planning", name: "Financial Planning" },
      { key: "services_investment_advisory", name: "Investment Advisory" },
      { key: "services_retirement_planning", name: "Retirement Planning" },
      { key: "services_estate_planning_financial", name: "Estate Planning (Financial)" },
      { key: "services_insurance_services", name: "Insurance Services" },
      { key: "services_life_insurance", name: "Life Insurance" },
      { key: "services_health_insurance", name: "Health Insurance" },
      { key: "services_auto_insurance", name: "Auto Insurance" },
      { key: "services_home_insurance", name: "Home Insurance" },
      { key: "services_business_insurance", name: "Business Insurance" },
      { key: "services_disability_insurance", name: "Disability Insurance" },
      { key: "services_mortgage_brokerage", name: "Mortgage Brokerage" },
      { key: "services_loan_services", name: "Loan Services" },
      { key: "services_debt_consolidation", name: "Debt Consolidation" },
      { key: "services_credit_repair", name: "Credit Repair" },
      { key: "services_financial_auditing", name: "Financial Auditing" },
      { key: "services_forensic_accounting", name: "Forensic Accounting" },
      { key: "services_business_valuation_financial", name: "Business Valuation (Financial)" },
      { key: "services_mergers_acquisitions_financial", name: "M&A Financial Services" },
      { key: "services_ipo_consulting", name: "IPO Consulting" },
      { key: "services_venture_capital", name: "Venture Capital" },
      { key: "services_private_equity", name: "Private Equity" },
      { key: "services_wealth_management", name: "Wealth Management" },
      { key: "services_family_office", name: "Family Office Services" },
      { key: "services_trust_services", name: "Trust Services" },
      
      // Event & Entertainment Services
      { key: "services_event_planning", name: "Event Planning" },
      { key: "services_wedding_planning", name: "Wedding Planning" },
      { key: "services_corporate_events", name: "Corporate Event Planning" },
      { key: "services_party_planning", name: "Party Planning" },
      { key: "services_birthday_parties", name: "Birthday Party Planning" },
      { key: "services_baby_shower", name: "Baby Shower Planning" },
      { key: "services_bridal_shower", name: "Bridal Shower Planning" },
      { key: "services_graduation_parties", name: "Graduation Party Planning" },
      { key: "services_anniversary_parties", name: "Anniversary Party Planning" },
      { key: "services_retirement_parties", name: "Retirement Party Planning" },
      { key: "services_holiday_parties", name: "Holiday Party Planning" },
      { key: "services_fundraising_events", name: "Fundraising Event Planning" },
      { key: "services_conference_planning", name: "Conference Planning" },
      { key: "services_trade_show_planning", name: "Trade Show Planning" },
      { key: "services_product_launches", name: "Product Launch Events" },
      { key: "services_award_ceremonies", name: "Award Ceremony Planning" },
      { key: "services_memorial_services", name: "Memorial Service Planning" },
      { key: "services_catering", name: "Catering" },
      { key: "services_wedding_catering", name: "Wedding Catering" },
      { key: "services_corporate_catering", name: "Corporate Catering" },
      { key: "services_kosher_catering", name: "Kosher Catering" },
      { key: "services_halal_catering", name: "Halal Catering" },
      { key: "services_vegan_catering", name: "Vegan Catering" },
      { key: "services_bbq_catering", name: "BBQ Catering" },
      { key: "services_food_trucks", name: "Food Truck Services" },
      { key: "services_bartending", name: "Bartending Services" },
      { key: "services_mobile_bar", name: "Mobile Bar Services" },
      { key: "services_dj_music", name: "DJ & Live Music" },
      { key: "services_wedding_dj", name: "Wedding DJ" },
      { key: "services_party_dj", name: "Party DJ" },
      { key: "services_corporate_dj", name: "Corporate DJ" },
      { key: "services_karaoke_dj", name: "Karaoke DJ" },
      { key: "services_live_bands", name: "Live Bands" },
      { key: "services_wedding_bands", name: "Wedding Bands" },
      { key: "services_cover_bands", name: "Cover Bands" },
      { key: "services_tribute_bands", name: "Tribute Bands" },
      { key: "services_jazz_bands", name: "Jazz Bands" },
      { key: "services_classical_musicians", name: "Classical Musicians" },
      { key: "services_string_quartets", name: "String Quartets" },
      { key: "services_solo_musicians", name: "Solo Musicians" },
      { key: "services_acoustic_performers", name: "Acoustic Performers" },
      { key: "services_dancers", name: "Dancers & Performers" },
      { key: "services_belly_dancers", name: "Belly Dancers" },
      { key: "services_ballroom_dancers", name: "Ballroom Dancers" },
      { key: "services_cultural_performers", name: "Cultural Performers" },
      { key: "services_magicians", name: "Magicians" },
      { key: "services_comedians", name: "Comedians" },
      { key: "services_entertainers", name: "Entertainers" },
      { key: "services_clowns", name: "Clowns" },
      { key: "services_face_painters", name: "Face Painters" },
      { key: "services_balloon_artists", name: "Balloon Artists" },
      { key: "services_puppet_shows", name: "Puppet Shows" },
      { key: "services_storytellers", name: "Storytellers" },
      { key: "services_motivational_speakers", name: "Motivational Speakers" },
      { key: "services_keynote_speakers", name: "Keynote Speakers" },
      { key: "services_mc_services", name: "MC Services" },
      { key: "services_venue_rental", name: "Venue Rental" },
      { key: "services_wedding_venues", name: "Wedding Venues" },
      { key: "services_party_venues", name: "Party Venues" },
      { key: "services_corporate_venues", name: "Corporate Venues" },
      { key: "services_outdoor_venues", name: "Outdoor Venues" },
      { key: "services_banquet_halls", name: "Banquet Halls" },
      { key: "services_event_spaces", name: "Event Spaces" },
      { key: "services_party_rentals", name: "Party Rentals" },
      { key: "services_tent_rentals", name: "Tent Rentals" },
      { key: "services_chair_rentals", name: "Chair Rentals" },
      { key: "services_table_rentals", name: "Table Rentals" },
      { key: "services_linen_rentals", name: "Linen Rentals" },
      { key: "services_china_rentals", name: "China & Glassware Rentals" },
      { key: "services_lighting_rentals", name: "Lighting Rentals" },
      { key: "services_sound_equipment_rentals", name: "Sound Equipment Rentals" },
      { key: "services_av_equipment_rentals", name: "AV Equipment Rentals" },
      { key: "services_staging_rentals", name: "Staging Rentals" },
      { key: "services_dance_floor_rentals", name: "Dance Floor Rentals" },
      { key: "services_photo_booth_rentals", name: "Photo Booth Rentals" },
      { key: "services_bounce_house_rentals", name: "Bounce House Rentals" },
      { key: "services_game_rentals", name: "Game Rentals" },
      { key: "services_decorations", name: "Event Decorations" },
      { key: "services_floral_arrangements", name: "Floral Arrangements" },
      { key: "services_wedding_flowers", name: "Wedding Flowers" },
      { key: "services_balloon_decorations", name: "Balloon Decorations" },
      { key: "services_centerpieces", name: "Centerpieces" },
      { key: "services_backdrops", name: "Backdrops" },
      { key: "services_custom_signage", name: "Custom Event Signage" },
      
      // Transportation & Logistics Services
      { key: "services_logistics_courier", name: "Logistics & Courier" },
      { key: "services_package_delivery", name: "Package Delivery" },
      { key: "services_same_day_delivery", name: "Same Day Delivery" },
      { key: "services_overnight_delivery", name: "Overnight Delivery" },
      { key: "services_international_shipping", name: "International Shipping" },
      { key: "services_freight_forwarding", name: "Freight Forwarding" },
      { key: "services_customs_brokerage", name: "Customs Brokerage" },
      { key: "services_warehousing", name: "Warehousing" },
      { key: "services_fulfillment", name: "Order Fulfillment" },
      { key: "services_distribution", name: "Distribution Services" },
      { key: "services_supply_chain", name: "Supply Chain Management" },
      { key: "services_inventory_management", name: "Inventory Management" },
      { key: "services_transportation", name: "Transportation Services" },
      { key: "services_trucking", name: "Trucking" },
      { key: "services_long_haul_trucking", name: "Long Haul Trucking" },
      { key: "services_local_trucking", name: "Local Trucking" },
      { key: "services_refrigerated_transport", name: "Refrigerated Transport" },
      { key: "services_hazmat_transport", name: "Hazmat Transport" },
      { key: "services_oversized_load", name: "Oversized Load Transport" },
      { key: "services_car_transport", name: "Car Transport" },
      { key: "services_motorcycle_transport", name: "Motorcycle Transport" },
      { key: "services_boat_transport", name: "Boat Transport" },
      { key: "services_rv_transport", name: "RV Transport" },
      { key: "services_equipment_transport", name: "Equipment Transport" },
      { key: "services_furniture_delivery", name: "Furniture Delivery" },
      { key: "services_appliance_delivery", name: "Appliance Delivery" },
      { key: "services_medical_transport", name: "Medical Transport" },
      { key: "services_ambulance", name: "Ambulance Services" },
      { key: "services_wheelchair_transport", name: "Wheelchair Transport" },
      { key: "services_airport_shuttle", name: "Airport Shuttle" },
      { key: "services_taxi", name: "Taxi Services" },
      { key: "services_rideshare", name: "Rideshare Services" },
      { key: "services_limo_service", name: "Limousine Services" },
      { key: "services_charter_bus", name: "Charter Bus Services" },
      { key: "services_school_bus", name: "School Bus Services" },
      { key: "services_party_bus", name: "Party Bus Services" },
      { key: "services_pedicab", name: "Pedicab Services" },
      { key: "services_bike_messenger", name: "Bike Messenger" },
      { key: "services_drone_delivery", name: "Drone Delivery" },
      
      // Travel & Tourism Services
      { key: "services_travel_agents", name: "Travel Agents" },
      { key: "services_travel_planning", name: "Travel Planning" },
      { key: "services_vacation_planning", name: "Vacation Planning" },
      { key: "services_honeymoon_planning", name: "Honeymoon Planning" },
      { key: "services_business_travel", name: "Business Travel Planning" },
      { key: "services_group_travel", name: "Group Travel Planning" },
      { key: "services_luxury_travel", name: "Luxury Travel Planning" },
      { key: "services_adventure_travel", name: "Adventure Travel Planning" },
      { key: "services_eco_travel", name: "Eco Travel Planning" },
      { key: "services_medical_tourism", name: "Medical Tourism" },
      { key: "services_visa_services", name: "Visa Services" },
      { key: "services_passport_services", name: "Passport Services" },
      { key: "services_travel_insurance", name: "Travel Insurance" },
      { key: "services_tour_guides", name: "Tour Guides" },
      { key: "services_walking_tours", name: "Walking Tours" },
      { key: "services_bus_tours", name: "Bus Tours" },
      { key: "services_boat_tours", name: "Boat Tours" },
      { key: "services_helicopter_tours", name: "Helicopter Tours" },
      { key: "services_wine_tours", name: "Wine Tours" },
      { key: "services_food_tours", name: "Food Tours" },
      { key: "services_historical_tours", name: "Historical Tours" },
      { key: "services_ghost_tours", name: "Ghost Tours" },
      { key: "services_photography_tours", name: "Photography Tours" },
      { key: "services_safari_tours", name: "Safari Tours" },
      { key: "services_cruise_planning", name: "Cruise Planning" },
      { key: "services_hotel_booking", name: "Hotel Booking" },
      { key: "services_vacation_rentals", name: "Vacation Rental Management" },
      { key: "services_timeshare", name: "Timeshare Services" },
      { key: "services_travel_concierge", name: "Travel Concierge" },
      { key: "services_destination_weddings", name: "Destination Wedding Planning" },
      
      // Real Estate Services
      { key: "services_real_estate", name: "Real Estate Services" },
      { key: "services_real_estate_agent", name: "Real Estate Agent" },
      { key: "services_buyer_agent", name: "Buyer's Agent" },
      { key: "services_listing_agent", name: "Listing Agent" },
      { key: "services_commercial_real_estate", name: "Commercial Real Estate" },
      { key: "services_investment_properties", name: "Investment Properties" },
      { key: "services_property_management", name: "Property Management" },
      { key: "services_rental_management", name: "Rental Management" },
      { key: "services_hoa_management", name: "HOA Management" },
      { key: "services_real_estate_appraisal", name: "Real Estate Appraisal" },
      { key: "services_home_inspection", name: "Home Inspection" },
      { key: "services_termite_inspection", name: "Termite Inspection" },
      { key: "services_radon_testing", name: "Radon Testing" },
      { key: "services_mold_inspection", name: "Mold Inspection" },
      { key: "services_lead_testing", name: "Lead Testing" },
      { key: "services_asbestos_testing", name: "Asbestos Testing" },
      { key: "services_real_estate_photography", name: "Real Estate Photography" },
      { key: "services_virtual_tours", name: "Virtual Tours" },
      { key: "services_3d_home_tours", name: "3D Home Tours" },
      { key: "services_real_estate_marketing", name: "Real Estate Marketing" },
      { key: "services_real_estate_staging", name: "Real Estate Staging" },
      { key: "services_mortgage_brokerage", name: "Mortgage Brokerage" },
      { key: "services_title_services", name: "Title Services" },
      { key: "services_escrow_services", name: "Escrow Services" },
      { key: "services_real_estate_law", name: "Real Estate Law" },
      { key: "services_property_tax_consulting", name: "Property Tax Consulting" },
      { key: "services_zoning_consulting", name: "Zoning Consulting" },
      { key: "services_land_development", name: "Land Development" },
      { key: "services_construction_management", name: "Construction Management" },
      
      // Consulting Services
      { key: "services_consulting", name: "Business Consulting" },
      { key: "services_startup_consulting", name: "Startup Consulting" },
      { key: "services_small_business_consulting", name: "Small Business Consulting" },
      { key: "services_nonprofit_consulting", name: "Nonprofit Consulting" },
      { key: "services_franchise_consulting", name: "Franchise Consulting" },
      { key: "services_retail_consulting", name: "Retail Consulting" },
      { key: "services_restaurant_consulting", name: "Restaurant Consulting" },
      { key: "services_hospitality_consulting", name: "Hospitality Consulting" },
      { key: "services_manufacturing_consulting", name: "Manufacturing Consulting" },
      { key: "services_healthcare_consulting", name: "Healthcare Consulting" },
      { key: "services_education_consulting", name: "Education Consulting" },
      { key: "services_government_consulting", name: "Government Consulting" },
      { key: "services_environmental_consulting", name: "Environmental Consulting" },
      { key: "services_sustainability_consulting", name: "Sustainability Consulting" },
      { key: "services_energy_consulting", name: "Energy Consulting" },
      { key: "services_security_consulting", name: "Security Consulting" },
      { key: "services_crisis_consulting", name: "Crisis Management Consulting" },
      { key: "services_turnaround_consulting", name: "Turnaround Consulting" },
      { key: "services_lean_consulting", name: "Lean Consulting" },
      { key: "services_six_sigma_consulting", name: "Six Sigma Consulting" },
      { key: "services_agile_consulting", name: "Agile Consulting" },
      { key: "services_digital_transformation", name: "Digital Transformation" },
      { key: "services_innovation_consulting", name: "Innovation Consulting" },
      { key: "services_diversity_consulting", name: "Diversity & Inclusion Consulting" },
      { key: "services_leadership_consulting", name: "Leadership Consulting" },
      { key: "services_executive_coaching", name: "Executive Coaching" },
      { key: "services_business_coaching", name: "Business Coaching" },
      { key: "services_sales_training", name: "Sales Training" },
      { key: "services_customer_service_training", name: "Customer Service Training" },
      { key: "services_communication_training", name: "Communication Training" },
      { key: "services_presentation_training", name: "Presentation Training" },
      { key: "services_negotiation_training", name: "Negotiation Training" },
      { key: "services_time_management_training", name: "Time Management Training" },
      { key: "services_stress_management", name: "Stress Management" },
      { key: "services_conflict_resolution", name: "Conflict Resolution" },
    ],
  },
];
